#!/usr/bin/env ruby
require 'open-uri'
require 'nokogiri'
require 'fileutils'

BASE_URL = 'https://atcoder.jp'.freeze
parent = File.basename(Dir.pwd)

doc = Nokogiri::HTML(open(BASE_URL + format('/contests/%s/tasks', parent)))
nodes = doc.xpath('/html/body/div[3]/div/div[1]/div[2]/div/table/tbody/tr')

problems = {}
nodes.each do |node|
  problem = node.xpath('.//td[1]/a')
  problems[problem.text] = problem[0][:href]
end

old_problems_flag = false

problems.each do |k, v|
  p_dir = format('data_%s', k.downcase)
  FileUtils.mkdir_p(p_dir)
  url = BASE_URL + format(v)
  p_doc = Nokogiri::HTML(open(url))

  xp = format('//div[@class="part"]/section/pre')
  samples = p_doc.xpath(xp)

  if samples.empty?
    xp = format('//div[@id="task-statement"]/section/pre')
    samples = p_doc.xpath(xp)
    old_problems_flag = true
  end

  if old_problems_flag
    start = 0
    count_max = samples.size
    start.upto(count_max - 1) do |count|
      filename_pref = count.even? ? 'sample_' : 'answer_'
      filename = filename_pref + (count / 2 + 1).to_s
      puts filename
      puts samples[count].text.strip
      File.open(p_dir + '/' + filename, 'wb').write(samples[count].text.strip.gsub(/\r\n/, "\n") + "\n")
    end
  else
    start = 1
    count_max = samples.size / 2
    start.upto(count_max - 1) do |count|
      filename_pref = count.odd? ? 'sample_' : 'answer_'
      filename = filename_pref + ((count + 1) / 2).to_s
      puts filename
      puts samples[count].text.strip
      File.open(p_dir + '/' + filename, 'wb').write(samples[count].text.strip.gsub(/\r\n/, "\n") + "\n")
    end
  end
end
