#!/usr/bin/env ruby
require 'open-uri'
require 'nokogiri'
require 'fileutils'

BASE_URL = 'https://atcoder.jp'.freeze
parent = File.basename(Dir.pwd)

doc = Nokogiri::HTML(open(BASE_URL + format('/contests/%s/tasks', parent)))
nodes = doc.xpath('/html/body/div[3]/div/div[1]/div[2]/div/table/tbody/tr')

problems = {}
nodes.each do |node|
  problem = node.xpath('.//td[1]/a')
  problems[problem.text] = problem[0][:href]
end

puts problems

problems.each do |k, v|
  p_dir = format('data_%s', k.downcase)
  FileUtils.mkdir_p(p_dir)
  url = BASE_URL + format(v)
  p_doc = Nokogiri::HTML(open(url))

  xp = format('//div[@class="part"]/section/pre')
  samples = p_doc.xpath(xp)
  count_max = samples.size / 2
  1.upto(count_max - 1) do |count|
    filename_pref = count.odd? ? 'sample_' : 'answer_'
    filename = filename_pref + ((count + 1) / 2).to_s
    puts filename
    puts samples[count].text
    File.open(p_dir + '/' + filename, 'wb').write(samples[count].text.chomp + "\n")
  end
end
